
name: Build SugarCube2

on:
  push:
    branches: [ "TS" ]
  pull_request:
    branches: [ "TS" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      matrix:
        # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
        os: [ ubuntu-latest ]
        #os: [ ubuntu-latest, windows-latest ]
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v3
        #with:
        #  submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          node build.js -d -u -b 2

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: SugarCube2 Package
          path: ${{ github.workspace }}/build/twine2/sugarcube-2/



